version: '3'
services:
  nuxt:
    build: .
    tty: true
    container_name: calambre
    command: npm run dev
    volumes:
      - ./src:/app
      - /app/client/node_modules
    ports:
      - "3000:3000"